### ISSUE TITLE
Add to Meltano Hub?

### ISSUE THREAD

**Issue by seajhawk** [jwills/target-duckdb#13]
**Is your feature request related to a problem? Please describe.**
This was the first custom plugin for Meltano that I have added and it took a fair bit of effort to figure out how to get it loaded. It would be much easier if it were on Meltano Hub so it could be installed via `meltano add`.

**Describe the solution you'd like**
For easier use with Meltano, my preference would be to have this added to https://hub.meltano.com/. 
Another option is to add Meltano-specific instructions to the project's `readme.md` with something like I have included in the "alternatives" below.

**Describe alternatives you've considered**
Here is what I did to get the plugin added:
```
meltano --no-environment add --custom loader target-duckdb

namespace: default [target_duckdb]
pip_url: default [target-duckdb]
executable: default [target-duckdb]
settings: default (no settings)
```

**Additional context**

**Comment by jwills** [comment]
Ha, I have had to do the same thing and I agree it's a PITA; will update the docs with a snippet of what a proper `meltano.yml` `loaders` entry looks like in the README (and I'll do the same for `dbt-duckdb` as a transformer, which is even more of a PITA to get right.)

**Comment by jwills** [comment]
Ah apparently the fine folks at Meltano are already on this for me; I'll link to the hub PR when it's ready!

**Comment by matsonj** [comment]
Pretty sure you can close this one :)

**Comment by seajhawk** [comment]
Yes I can! I've enjoyed using it!

For any that find this issue, here the link: https://hub.meltano.com/loaders/target-duckdb
