### ISSUE TITLE
Fully qualified path error

### ISSUE THREAD

**Issue by jaypeedevlin** [jwills/target-duckdb#21]
**Describe the bug**

It's not clear whether this is a Meltano issue or a duckdb issue, I'm getting the following error when I try to load data using a recent installation of target-duckdb

```
duckdb.BinderException: Binder Error: Ambiguous reference to catalog or schema "myschema" - use a fully qualified path like "myschema.myschema"`
```

**To Reproduce**
1. Use a clean installation of target-duckdb in Meltano
2. Send some data through the target
3. When the target tries to create a table, it raises the error above.

**Expected behavior**
When I change the `load_schema` property in Meltano from `myschema` to `myschema.myschema`, everything works as expected. Using an earlier installation of target-duckdb (same version of the target but installs an earlier version of duckdb itself) it worked fine defining that property as `myschema` only.

**Screenshots**

**Your environment**
 - Version of target: 0.4.4
 - Version of python 3.10

**Additional context**
I'm happy with my workaround as above, just wanted to flag this in-case it was an issue on the target side worth fixing.

**Comment by jwills** [comment]
0.5.0 is now up on pypi with the fix!
