### ISSUE TITLE
Could a git tag / github release be created for the 0.6.0 PyPI release?

### ISSUE THREAD

**Issue by edgarrmondragon** [jwills/target-duckdb#31]
Last tag is 0.5.0.

**Comment by jwills** [comment]
Ack, lame-- apparently I was testing 0.6.1 back in the day?

https://github.com/jwills/target-duckdb/pull/27

**Comment by jwills** [comment]
Then I think I left for vacation and promptly forgot all about this-- sorry!

**Comment by jwills** [comment]
Okay, 0.6.0 is now tagged
