### ISSUE TITLE
Support duckdb 0.10+

### ISSUE THREAD

**Issue by edgarrmondragon** [jwills/target-duckdb#40]
**Is your feature request related to a problem? Please describe.**

This target currently has a constraint on duckdb 0.9.2, but it'd be nice to have support for recent releases of duckdb (0.10+). This is a requirement for, among other things, enabling [Python 3.12 support](https://github.com/duckdb/duckdb/commit/a21a2727d6b2dee6ccd150dbebb84b26bc59aee5).

**Describe the solution you'd like**

Bump the dependency or make it a range (e.g. `>=0.9.2`).

**Describe alternatives you've considered**

Continue using duckdb 0.9.2 😅 

**Additional context**

I figure this is probably blocked in part by [MotherDuck's currently supported version](https://motherduck.com/docs/troubleshooting/faq/#how-do-i-know-which-version-of-duckdb-i-should-be-running-), but I wanted to log so myself and maybe others can keep track of it.

Thanks!

**Comment by jwills** [comment]
Yeah I was waiting here on MotherDuck to support it, but I think that's ready now so will fix this and cut a new release in the next couple of days

**Comment by edgarrmondragon** [comment]
Thanks, do let me know if I can help!

**Comment by jwills** [comment]
Okay, just released 0.7.0: https://pypi.org/project/target-duckdb/

**Comment by edgarrmondragon** [comment]
> Okay, just released 0.7.0: https://pypi.org/project/target-duckdb/

Works great, feel free to close!
